def req(url, body) {
    return httpRequest(authentication: 'shariktlt_school_devops', url: url, requestBody: body)
}

def comment(text) {
    req("${COMMENTS_URL}", "{\"content\":{\"raw\": \"${text}\"}}")
}

pipeline {
  agent any

  parameters {
          string(name: 'SOURCE_SCM', default: '')
          string(name: 'TARGET_SCM', default: '')
          string(name: 'PR_OWNER', default: '')
          string(name: 'COMMENTS_URL', default: '')

      }





  stages {
  stage('Build') {
      steps {

        echo 'Building...'
        comment('Start building')
        echo "SOURCE_SCM = '${SOURCE_SCM}'"
        echo "TARGET_SCM = '${TARGET_SCM}'"
        echo "PR_OWNER = '${PR_OWNER}'"
        echo "COMMENTS_URL = '${COMMENTS_URL}'"

      }
    }
  }
}